jobs:
  deploy:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       
      - name: Build and Deploy
        run: npm run build
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }},
          SIGNUP_CODE: ${{ secrets.SIGNUP_CODE }}
